sudo: false  # to run on the new travis container infrastructure
language: ruby
addons:
  apt:
  packages:
    - idn
    - build-essential  # this and following ensure rubinius is setup ok
    - bison
    - ruby-dev
    - rake
    - lib1g-dev
    - libyaml-dev
    - libssl-dev
    - libreadline-dev
    - libncurses5-dev
    - llvm
    - llvm-dev
    - libeditline-dev
    - libedit-dev
rvm:
  - 2.3
  - jruby
